### ISSUE TITLE
Hi, I have some questions as follow.

### ISSUE THREAD

**Issue by Woooooody** [akjindal53244/dependency_parsing_tf#1]
1.have you use the feature of corresponding arc labels of words? I can't find this section in your code. 
2.why you not use the **cube activation function**? 
3.whether you have achieved the same performance as the paper(UAS test:92.0)
                                                                                                                         thank you !
                                                                                                                         from China : )

**Comment by akjindal53244** [comment]
Hi Woooooody,
Thanks for showing interest. I recently started working on this :)

**1. have you use the feature of corresponding arc labels of words? I can't find this section in your code.**
As of now, I am not using arc labels as features. (word + pos) combination is shown to perform equivalently to (word + pos + label) combination for UAS.

**2.why you not use the cube activation function?**
Thanks for pointing out. Current implementation uses ReLU as activation function. I will try to add cube activation function since paper shows good improvement if we use cube activation function.

**3.whether you have achieved the same performance as the paper(UAS test:92.0)?**
As of now, I am getting accuracy of ~88% on both valid & test. At current, word embeddings are non-trainable. I will try to experiment will different embeddings also.

This is initial implementation and further work needs to be done from performance perspective :) 
If you have any thoughts, feel free to comment. I will try to integrate the changes.

Thanks,
Ashvini

**Comment by akjindal53244** [comment]
I have made commit with following changes:
1. Cube Activation function and dependency labels as features.
2. Test UAS: 90.42
3. transition to tensorflow 1.2

Let me know if you find any issue or you have any further inputs. I will close the issue then.

**Comment by Woooooody** [comment]
I have been download your code. I will ask you later, if I have any question. All in all ,very appreciated for you help. It's really helpful to me.
